.authenticate-npm:
  - &authenticate-npm |
    echo "$NPM_SCOPE:registry=https://$NPM_REGISTRY_HOST/" >> ~/.npmrc
    echo "//$NPM_REGISTRY_HOST/:_authToken=$NPM_TOKEN" >> ~/.npmrc

before_script:
  - node --version
  - npm --version

variables:
  CLOUDSMITH_API_KEY: $CLOUDSMITH_API_KEY

stages:
  - build
  - publish

build-10.3.0:
  image: node:10.3.0-alpine
  stage: build
  script:
    - *authenticate-npm
    - npm run build

build-11.0.0:
  image: node:11.0.0-alpine
  stage: build
  script:
    - *authenticate-npm
    - npm run build

build-12.0.0:
  image: node:12.0.0-alpine
  stage: build
  script:
    - *authenticate-npm
    - npm run build

build-13.7.0:
  image: node:13.7.0-alpine
  stage: build
  script:
    - *authenticate-npm
    - npm run build

build-14.0.0:
  image: node:14.0.0-alpine
  stage: build
  script:
    - *authenticate-npm
    - npm run build

publish:
  stage: publish
  image: node:12-alpine
  script:
    - *authenticate-npm
    - npm ci
    - npm run make-distribution
    - npm publish --verbose --tag sha-$CI_COMMIT_SHORT_SHA
    - RM_TMP_TAG=sha-$CI_COMMIT_SHORT_SHA RM_KEEP_TMP_TAG=1 ./tag-nodejs
  only:
    - /^\d+\.\d+\.\d+(\-[^\.]+\.\d+)?$/
