before_script:
  - node --version
  - npm --version

stages:
  - build
  - publish

build-10.3.0:
  image: node:10.3.0-alpine
  stage: build
  script:
    - npm run build

build-11.0.0:
  image: node:11.0.0-alpine
  stage: build
  script:
    - npm run build

build-12.0.0:
  image: node:12.0.0-alpine
  stage: build
  script:
    - npm run build

build-13.7.0:
  image: node:13.7.0-alpine
  stage: build
  script:
    - npm run build

build-14.0.0:
  image: node:14.0.0-alpine
  stage: build
  script:
    - npm run build

publish:
  stage: publish
  image: node:12-alpine
  script:
    - export NPM_SCOPE=$(node -e 'console.log(require("./package.json").name.split("/")[0])')
    - npm config set $NPM_SCOPE:registry https://gitlab.com/api/v4/packages/npm/
    - npm config set //gitlab.com/api/v4/packages/npm/:_authToken ${CI_JOB_TOKEN}
    - npm config set //gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken ${CI_JOB_TOKEN}
    - npm ci
    - npm run make-distribution
    - npm publish --verbose --tag $CI_COMMIT_SHORT_SHA
    - ./tag-nodejs
  only:
    - /^\d+\.\d+\.\d+(\-[^\.]+\.\d+)?$/
